import type { Metadata } from "next";
import { VotacaoContextProvider } from "../contexts/VotacaoContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Enquete de satisfação",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/moema.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <VotacaoContextProvider>
        <body>
          {children}
        </body>
      </VotacaoContextProvider>
    </html>
  );
}
